### ISSUE TITLE
关于刷日期的屏蔽规则

### ISSUE THREAD

**Issue by jnxyp** [jnxyp/Bilibili-Block-List#2]
现有的规则误伤较为严重，而且缺乏对于类似 ”20160914“ 类弹幕的屏蔽，希望有高人能够帮助改进。

**Comment by jnxyp** [comment]
现已添加对于 ”20160914“ 类弹幕的临时屏蔽规则
`^\s{0,}((19|2[0-9])[1-9]{2}|[1-9]{2})(0[1-9]|1[12])([012][1-9]|3[01])`

**Comment by xmcp** [comment]
https://github.com/xmcp/bilibili-ban-list/blob/master/tv.bilibili.player.xml#L51-L54

个人感觉这些规则误报、漏报是比较少的
