### ISSUE TITLE
感觉正则屏蔽没有正常启动

### ISSUE THREAD

**Issue by miciix** [jnxyp/Bilibili-Block-List#4]
HTML5播放器现在可以导入xml文件了，但是导入后没有看到弹幕被屏蔽。

**Comment by jnxyp** [comment]
@qq413759591 
终于添加了啊....我还以为B站不打算弄这个功能了.....
你说的问题的确存在，是因为每条规则前面 “(?#  ) ” 里的注释造成的，貌似B站的H5播放器不支持注释语法
俺这周末会修复一下，在这之前可以暂时把前面的注释删掉使用
谢谢你的问题反馈！

**Comment by sola97** [comment]
html5这个导入和油猴的网页限制解除脚本冲突，怪不得我找不到功能
