### ISSUE TITLE
B站Flash播放器改了,增加了一类正则

### ISSUE THREAD

**Issue by sola97** [jnxyp/Bilibili-Block-List#5]
旧规则会识别为文本，导致失效
正则有条数限制，大概是100条以上就无法添加了
每条规则长度限制50个字

**Comment by marcosteam** [comment]
HTML5播放器快成为正统了吧？

**Comment by sola97** [comment]
有时html5缓冲不如flash流畅，我基本是切换着用的

**Comment by jnxyp** [comment]
B站的系统真的是.....换播放器还能影响视频缓冲.....
两个播放器不同步也是很烦..... 本来想H5版可以和Flash通用的呢......

**Comment by chenyangsang** [comment]
昨天刚刚问了前端工程师，说是以后H5版也会同步。。醉了，要是这样的话以后正则也不好用了，还怎么愉快的看视频啊。。

**Comment by jnxyp** [comment]
@chenyangsang 
嗯，确定会同步的话就按照新的标准来改了，不过最近太忙没大有空
另外谢谢提供屏蔽列表
